"""
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting
with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the
sum of the even-valued terms.
"""


def sum_even_fib(cap: int = 4_000_000) -> int:
    """Calculate the sum of the even-valued termes of the Fibonacci sequence below `cap`."""
    a = 0
    b = 1
    val = a + b
    even_sum = 0
    while val <= cap:
        if val % 2 == 0:
            even_sum += val

        a, b = b, val
        val = a + b

    return even_sum


if __name__ == "__main__":
    print(f"Solution: {sum_even_fib()}")
